/**
 * Created by wuxiaoran on 2017/8/16.
 */

// route: /api/patient/user

const jsonwebtoken  = require('jsonwebtoken');
const jwt = require('express-jwt');
const config = require('../config');

module.exports = {
  /*
   Will be translated to get("/people") (first level is generated by controller name)
   */
  get_index : [jwt({secret: config.token.secret}), function(req, res) {
    res.json({
      status: 'success',
      data: null,
    });
  }],

  /*
   Will be translated to get("/people") (HTTP-method is extracted by first item in function name)
   */
  post_index : function(req, res) {
    res.send("People index page post method test");
  },

  /*
   Will be translated to get("/people/:id") (parameters automatically extracted from function parameters)
   */
  get_id : function(req, res, id) {
    res.send("You are requesting the resource with id: " + id);
  },

  /*
   Will be translated to get("/people/:id/friends") (if parameter is included in function-name, it will be be included in the same position)
   */
  get_id_friends : function(req, res, id) {
    res.send("You are requesting the friends of the person with id: " + id);
  },
  /*
   Will be translated to get("/people/:userName/friend-requests") (non parameter parts that use camelCase will be separated by hyphens in the url)
   */
  get_userName_friendRequests : function(req, res, userName) {
    res.send("You are requesting the friend requests of the person with user name: " + userName);
  }
}